"""add reader artifact fields and reading progress table

Revision ID: 762200b77a49
Revises: c3b6f41f3995
Create Date: 2026-09-24 11:10:51.321805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762200b77a49'
down_revision: Union[str, None] = 'c3b6f41f3995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.String(length=128), nullable=False),
    sa.Column('character_offset', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'book_id', name='uq_reading_progress_owner_book')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reader_artifact_storage_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('reader_artifact_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('reader_artifact_version')
        batch_op.drop_column('reader_artifact_storage_key')

    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_owner_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_book_id'))

    op.drop_table('reading_progress')
    # ### end Alembic commands ###
