"""add epub storage fields to books

Revision ID: c3b6f41f3995
Revises: 16a11bac3fe5
Create Date: 2026-09-24 10:25:59.779489

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3b6f41f3995'
down_revision: str | None = '16a11bac3fe5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epub_storage_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('epub_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('epub_version')
        batch_op.drop_column('epub_storage_key')

    # ### end Alembic commands ###
